<a href="https://colab.research.google.com/github/arbeeorlar/data_science/blob/main/helloWorld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#my comment
#see my comment
print("Hello world.... My first python code")

numberA = 10
numberB = 12

sum = numberA + numberB

print('The sum is = ', sum)

integer_number = "123"
float_number = 12.4

result = int (integer_number) * float_number

print("the answer is ", result)
print("Integer Type ", int (integer_number))

print('Good Morning!', sep= '45')

print('New Year', 2023, 'See you soon!', sep= '% ')

# using input() to take user input
num = input('Enter a number: ')

print('You Entered:', num)

print('Data type of num:', type(num))

_candy = 2

HELLO = 5

me_you = 6

#my comment
#see my comment
print("Hello world.... My first python code")

numberA = 10
numberB = 12

sum = numberA + numberB

print('The sum is = ', sum)

integer_number = "123"
float_number = 12.4

result = int (integer_number) * float_number

print("the answer is ", result)
print("Integer Type ", int (integer_number))

print('Good Morning!', sep= '45')

print('New Year', 2023, 'See you soon!', sep= '% ')

# using input() to take user input
num = int(input('Enter a number: '))

print('You Entered:', num)

print('Data type of num:', type(num))

if num > 10:
   print("you")
else:
   print("me")


# iterate from i = 0 to i = 3
for i in range(0, 4):
    print(i)


## slicing array

my_list = ['p', 'r', 'o', 'g', 'r', 'a', 'm']
print("my_list =", my_list)

# get a list with items from index 2 to index 4 (index 5 is not included)
print("my_list:::1[2: 5] =", my_list[2: 5])

# get a list with items from index 2 to index -3 (index -2 is not included)
print("my_list:::2[2: -2] =", my_list[2: -2])

# get a list with items from index 0 to index 2 (index 3 is not included)
print("my_list:::3[0: 3] =", my_list[0: 3])

#copying an array to another array
numbers = [1, 3, 5]
print('Numbers:', numbers)

even_numbers  = [2, 4, 6]
print('Even numbers:', even_numbers)

# adding elements of one list to another
numbers.extend(even_numbers)

print('Updated Numbers:', numbers)

#set
numbers = {2, 4, 6, 6, 2, 8}
print(numbers)   # {8, 2, 4, 6}


#function

# function with two arguments
def add_numbers(num1, num2):
    sum = num1 + num2
    print("Sum: ", sum)

# function call with two values
add_numbers(5, 4)

if(even_numbers.length == 2 or eve){


}


print("The result of the function is ",add_numbers(5, 4))



Hello world.... My first python code
The sum is =  22
the answer is  1525.2
Integer Type  123
Good Morning!
New Year% 2023% See you soon!
Enter a number: 656
You Entered: 656
Data type of num: <class 'str'>
Hello world.... My first python code
The sum is =  22
the answer is  1525.2
Integer Type  123
Good Morning!
New Year% 2023% See you soon!
Enter a number: 78
You Entered: 78
Data type of num: <class 'int'>
you
0
1
2
3
my_list = ['p', 'r', 'o', 'g', 'r', 'a', 'm']
my_list:::1[2: 5] = ['o', 'g', 'r']
my_list:::2[2: -2] = ['o', 'g', 'r']
my_list:::3[0: 3] = ['p', 'r', 'o']
Numbers: [1, 3, 5]
Even numbers: [2, 4, 6]
Updated Numbers: [1, 3, 5, 2, 4, 6]
{8, 2, 4, 6}
Sum:  9
Sum:  9
The result of the function is  None


In [ ]:
import numpy as np

In [ ]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [ ]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [ ]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
demo_array = np.arange(0,10)
demo_array
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
import pandas as pd

In [ ]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers

lily     2
rose     3
daisy    5
lotus    4
dtype: int64

In [ ]:
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

In [ ]:
data_customer.loc[1:2, ['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [ ]:
data_cust = pd.DataFrame({
    'customer': [101, 102, 103, 104, 101, 103],
    'category': ['cat2', 'cat2', 'cat1', 'cat3', 'cat2', 'cat1'],
    'important': ['yes', 'no', 'yes', 'yes', 'yes', 'yes'],
    'sales': [123, 52, 214, 663, 204, 453]
})

In [ ]:
data_cust.groupby(['customer'])['sales'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64